# Generated by Django 4.1.2 on 2022-11-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_carowner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
