# Generated by Django 4.1.3 on 2023-01-08 21:37

from django.db import migrations, models
import parking.models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_carowner_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='idcarowner',
        ),
        migrations.AlterField(
            model_name='car',
            name='productionyear',
            field=models.IntegerField(validators=[parking.models.validate_productionyear]),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='email',
            field=models.CharField(max_length=45, validators=[parking.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[parking.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='parkingplaces',
            name='placenumber',
            field=models.IntegerField(validators=[parking.models.validate_placenumber]),
        ),
    ]
