# Generated by Django 4.1.3 on 2023-01-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplaces',
            name='car_registrynumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkingplaces', to='products.car'),
        ),
        migrations.AlterField(
            model_name='parkingplaces',
            name='dateofpurchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
