# Generated by Django 4.1.3 on 2023-01-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_parkingplaces_car_registrynumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='carregistrynumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carowner', to='products.car'),
        ),
    ]
